/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.greens.VoterContactManager

/**
 *
 * @author jam
 */
class StateVoterFields {
    static fields = [
        'FL': [
            "County Code",
            "Voter ID",
            "Name Last",
            "Name Suffix",
            "Name First",
            "Name Middle",
            "Suppress Address",
            "Residence Address Line 1",
            "Residence Address Line 2",
            "Residence City USPS",
            "Residence State",
            "Residence Zipcode",
            "Mailing Address Line 1",
            "Mailing Address Line 2",
            "Mailing Address Line 3",
            "Mailing City",
            "Mailing State",
            "Mailing Zipcode",
            "Mailing Country",
            "Gender",
            "Race",
            "Birth Date",
            "Registration Date",
            "Party Affiliation",
            "Precinct",
            "Precinct Group",
            "Precinct Split",
            "Precinct Suffix",
            "Voter Status",
            "Congressional District",
            "House District",
            "Senate District",
            "County Commission District",
            "School Board District",
            "Daytime Area Code",
            "Daytime Phone Number",
            "Daytime Phone Extension",
            "Export Date"
        ],
        'GA': [
            'COUNTY-CODE',
            'REGISTRATION-NBR',
            'VOTER-STATUS',
            'VOTER-LAST-NAME',
            'VOTER-FIRST-NAME',                      
            'VOTER-MIDDLE-MAIDEN',         
            'VOTER-NAME-SUFFIX',                 
            'VOTER-NAME-TITLE',                      
            'RES-HOUSE-NBR',
            'RES-STREET-NAME',
            'RES-STREET-SUFFIX',
            'RES-APT-UNIT-NBR',
            'RES-CITY-NAME',
            'RES-ZIP',
            'RES-ZIP-PLUS4',
            'DATE-OF-BIRTH',
            'REGISTRATION-DATE',
            'RACE',
            'GENDER',
            'ABSENTEE',
            'LAND-DISTRICT',
            'LAND-LOT',
            'OLD-REG-DATE',
            'OLD-REG-NBR',
            'COUNTY-PRECINCT-ID',
            'CITY-PRECINCT-ID',
            'CONGRESSIONAL-DIST',
            'SENATE-DIST',
            'HOUSE-DIST',
            'JUDICIAL-DIST',
            'COMM-DIST',
            'SCHOOL-DIST',
            'COUNTY-DISTA-NAME',
            'COUNTY-DISTA-VALUE',
            'COUNTY-DISTB-NAME',
            'COUNTY-DISTB-VALUE',
            'MUNICIPAL-NAME',
            'MUNICIPAL-CODE',
            'WARD-CITY-COUNCIL-NAME',
            'WARD-CITY-COUNCIL',
            'CITY-SCHOOL-DIST-NAME',
            'CITY-SCHOOL-DIST',
            'CITY-DISTA-NAME',
            'CITY-DISTA-VALUE',
            'CITY-DISTB-NAME',
            'CITY-DISTB-VALUE',
            'CITY-DISTC-NAME',
            'CITY-DISTC-VALUE',
            'CITY-DISTD-NAME',
            'CITY-DISTD-VALUE',
            'DATE-LAST-VOTED-DATE',
            'TYPE-OF-ELECTION',
            'PARTY-LAST-VOTED',
            'LAST-CONTACT-DATE',
            'MAIL-HOUSE-NBR',
            'MAIL-STREET-NAME',
            'MAIL-STREET-SUFFIX',
            'MAIL-APT-UNIT-NBR',
            'MAIL-CITY',
            'MAIL-STATE',
            'MAIL-ZIP',
            'MAIL-ZIP-PLUS4',
            'MAIL-ADDRESS-2',
            'MAIL-ADDRESS-3',
            'MAIL-COUNTRY',
            'DATE-ADDED',
            'DATE-CHANGED',
            'DISTRICT-COMBO',
            'RES-BUILDING',
            'MAIL-RR-PO-BOX',
            'COMBINED-STREET-ADDR'                                        
        ]
    ]
}

