/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.greens.VoterContactManager

/**
 *
 * @author jam
 */
class StateVoterFields {
    static fields = [
        'FL': [
            "County Code",
            "Voter ID",
            "Name Last",
            "Name Suffix",
            "Name First",
            "Name Middle",
            "Suppress Address",
            "Residence Address Line 1",
            "Residence Address Line 2",
            "Residence City USPS",
            "Residence State",
            "Residence Zipcode",
            "Mailing Address Line 1",
            "Mailing Address Line 2",
            "Mailing Address Line 3",
            "Mailing City",
            "Mailing State",
            "Mailing Zipcode",
            "Mailing Country",
            "Gender",
            "Race",
            "Birth Date",
            "Registration Date",
            "Party Affiliation",
            "Precinct",
            "Precinct Group",
            "Precinct Split",
            "Precinct Suffix",
            "Voter Status",
            "Congressional District",
            "House District",
            "Senate District",
            "County Commission District",
            "School Board District",
            "Daytime Area Code",
            "Daytime Phone Number",
            "Daytime Phone Extension",
            "Export Date"
        ],
        'GA': [
            'County Code',
            'Voter ID',
            'Voter Status',
            'Name Last',
            'Name First',                      
            'Name Middle',         
            'Name Suffix',                 
            'Name Salutation',                      
            "Residence Address Line 1",
            "Residence Address Line 2",
            "Residence City USPS",
            "Residence State",
            "Residence Zipcode",
            "Birth Date",
            "Registration Date",
            "Race",
            "Gender",
            'Absentee',
            'Land District',
            'Land Lot',
            'Old Registration Date',
            'Old Voter ID',
            'County Precinct ID',
            'City Precinct ID',
            "Congressional District",
            "Senate District",
            "House District",
            'Judicial District',
            "County Commission District",
            "School Board District",
            'County District A Name',
            'County District A Value',
            'County District B Name',
            'County District B Value',
            'Municipal Name',
            'Municipal Code',
            'Ward City Council Name',
            'Ward City Council',
            'City School District Name',
            'City School District',
            'City District A Name',
            'City District A Value',
            'City District B Name',
            'City District B Value',
            'City District C Name',
            'City District C Value',
            'City District D Name',
            'City District D Value',
            'Last Voted Date',
            'Last Election Type',
            'Last Party Voted',
            'Last Contact Date',
            "Mailing Address Line 1",
            "Mailing Address Line 2",
            "Mailing Address Line 3",
            "Mailing City",
            "Mailing State",
            "Mailing Zipcode",
            "Mailing Country",
            'Date Added',
            'Date Changed',
            'District Combo',
            'Residence Building Designation',
            'Mail Address Rural Route Or POB',
            'Combined Street Address',                                        
            "Export Date"
        ]
    ]
}

